---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-todo-sarmag-co-v1-todolist
  failurePolicy: Fail
  name: vtodolist.kb.io
  rules:
  - apiGroups:
    - todo.sarmag.co
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - todolists
  sideEffects: None
