# permissions for end users to edit todolists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: todolist-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operators
    app.kubernetes.io/part-of: k8s-operators
    app.kubernetes.io/managed-by: kustomize
  name: todolist-editor-role
rules:
- apiGroups:
  - todo.sarmag.co
  resources:
  - todolists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - todo.sarmag.co
  resources:
  - todolists/status
  verbs:
  - get
